export const POSTS = 
    [
        {
            id: 0,
            name:'गुफ़त्गू',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-1.jpg',
            artistFollowers: '100',
            image: '/img/Soham 100 Images/img_1.jpg',
            category: 'image',
            date:'Mar 25, 2021',
            likes:'12k',
            views:'20k',
            type: 'Image',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',
        },
        {
            id: 1,
            name:'LANDSCAPE',
            artistName: 'NAV KANT',
            artistImg:'/img/user-2.jpg',
            artistFollowers: '10',
            image: '/img/Soham 100 Images/img_2.jpg',
            category: 'image',
            date:'Mar 14, 2021',
            likes:'1k',
            views:'2k',
            type: 'Image',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',                     
        },
        {
            id: 2,
            name:'PASSING',
            artistName: 'SONALI BOSE',
            artistImg:'/img/user-3.jpg',
            artistFollowers: '250',
            image: '/img/Soham 100 Images/img_3.jpg',
            category: 'videos',
            date:'Mar 22, 2021',
            likes:'15k',
            views:'40k',
            type: 'Image',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',      
        },
        {
            id: 3,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '150',
            image: '/img/Soham 100 Images/img_4.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Video',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',
        },
        {
            id: 4,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '130',
            image: '/img/Soham 100 Images/img_4.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Video',
            description:'The name itself  bears impression of intense brainstorming ',                   
        },
        {
            id: 5,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '120',
            image: '/img/Soham 100 Images/img_5.jpeg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Video',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',                  
        },
        {
            id: 6,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '500',
            image: '/img/Soham 100 Images/img_6.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Audio',
            description:'Impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',                  
        },
        {
            id: 7,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '300',
            image: '/img/Soham 100 Images/img_7.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Audio',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor' ,                
        },
        {
            id: 8,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '600',
            image: '/img/Soham 100 Images/img_8.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Audio',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as `The name should have Indian flavor',                  
        },
        {
            id: 9,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '700',
            image: '/img/Soham 100 Images/img_9.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Audio',
            description:'Sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',                    
        },
        {
            id: 10,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '800',
            image: '/img/Soham 100 Images/img_10.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Image',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',                   
        },
        {
            id: 11,
            name:'NARI NARAYANI',
            artistName: 'Sergii Miloskiy',
            artistImg:'/img/user-4.jpg',
            artistFollowers: '900',
            image: '/img/Soham 100 Images/img_11.jpg',
            category: 'audio',
            date:'Mar 12, 2021',
            likes:'1k',
            views:'3k',
            type: 'Image',
            description:'The name itself  bears impression of intense brainstorming sessions which went on for months as it was decided from the very first day that `The name should have Indian flavor',        
        },

    ]